### ISSUE TITLE
All our logs get truncated after upgrading to 2.1.0

### ISSUE THREAD

**Issue by NickMihaiu91** [loggly/node-loggly-bulk#28] opened 2017-11-16 14:07 UTC
Hello,

We upgraded today from version 2.0.0 to the latest 2.1.0 and all our logs look like this:
`{"level":"error","tag":"server","message":"Unhandled promise rejection: socket hang up","meta":{"error":{"message":"socket hang up","stack":"Error: socket hang up\n    at createHangUpError (_http_client.js:253:15)\n    at TLSSocket.socketOnEnd (_http_client.js:345:23)\n    at emitNone (events.js:91:20)\n    at TLSSocket.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (inter`

They look truncated and we get a lot of them, like 20k/hour. 
We were thinking it might be because of this:
https://github.com/loggly/node-loggly-bulk/commit/4851a178e10b82481c42b9f6495cca599f8065e7

Reverting to 2.0.0 fixed the problem.
Any ideas on what the problem in this new version is?

Thank you!

**Comment by mostlyjason** [comment] 2017-11-16 17:51
I believe the latest is actually 2.2.0 https://www.npmjs.com/package/node-loggly-bulk. We rolled 2.1.0 back by publishing 2.2.0. This is a known problem described on #10 and we are working to fix it. Closing this issue because it's a duplicate of #10

**Closed by mostlyjason** 2017-11-16 17:51 UTC
